/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "obsidian-bg": "#090A0C",
        "tertiary-container": "#dfe2ed",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#506600",
        "secondary": "#c6c6cc",
        "secondary-fixed": "#e2e2e8",
        "surface-container-high": "#292a2c",
        "tertiary-fixed-dim": "#c3c6d1",
        "on-primary-fixed": "#161e00",
        "surface-container-lowest": "#0d0e10",
        "surface-variant": "#343537",
        "surface": "#121315",
        "muted-text": "#6B7280",
        "primary-container": "#c3f400",
        "surface-container": "#1f2022",
        "primary-fixed": "#c3f400",
        "error": "#ffb4ab",
        "surface-bright": "#38393b",
        "on-secondary-fixed-variant": "#45474b",
        "inverse-surface": "#e3e2e5",
        "tertiary": "#ffffff",
        "surface-container-low": "#1b1c1e",
        "charcoal-surface": "#111317",
        "secondary-container": "#47494e",
        "primary-fixed-dim": "#abd600",
        "primary": "#ffffff",
        "grid-line": "#22262E",
        "background": "#121315",
        "outline-variant": "#444933",
        "on-background": "#e3e2e5",
        "acid-lime-dim": "#A3CC00",
        "on-tertiary": "#2c3039",
        "tertiary-fixed": "#dfe2ed",
        "surface-dim": "#121315",
        "on-secondary-fixed": "#1a1c20",
        "on-surface": "#e3e2e5",
        "outline": "#8e9379",
        "error-container": "#93000a",
        "on-primary": "#283500",
        "on-tertiary-fixed": "#181c23",
        "on-primary-container": "#556d00",
        "on-secondary": "#2f3035",
        "secondary-fixed-dim": "#c6c6cc",
        "inverse-on-surface": "#303033",
        "on-primary-fixed-variant": "#3c4d00",
        "acid-lime-hover": "#D9FF33",
        "on-tertiary-fixed-variant": "#434750",
        "on-secondary-container": "#b7b8bd",
        "surface-container-highest": "#343537",
        "on-tertiary-container": "#61646e",
        "on-surface-variant": "#c4c9ac",
        "on-error": "#690005",
        "surface-tint": "#abd600"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "bento-gap": "16px",
        "space-lg": "32px",
        "space-sm": "8px",
        "grid-margin": "40px",
        "space-xs": "4px",
        "space-xl": "64px",
        "grid-gutter": "1px",
        "space-md": "16px"
      },
      fontFamily: {
        "headline-xl": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "mono-technical": ["JetBrains Mono"],
        "headline-xl-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "mono-index": ["JetBrains Mono"]
      },
      fontSize: {
        "headline-xl": ["72px", { "lineHeight": "1.0", "letterSpacing": "-0.05em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "mono-technical": ["13px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-xl-mobile": ["42px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "body-md": ["15px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "mono-index": ["11px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
